# Generated by Django 5.0.4 on 2024-05-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durag_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_managerelated_namer',
            new_name='is_manager',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='nmae',
            new_name='name',
        ),
    ]
